# Generated by Django 4.2.28 on 2026-02-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='notification_preference',
            field=models.CharField(choices=[('ALL', 'All Notifications'), ('CRITICAL', 'Critical Only (High/Critical Priority + Blocked Tickets)'), ('NONE', 'No Notifications')], default='ALL', help_text='Email notification preference level', max_length=10),
        ),
    ]
