# Generated by Django 6.0.3 on 2026-03-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('human', 'Human'), ('bot', 'Bot')], max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exceptions', to=settings.AUTH_USER_MODEL)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_from', to='tickets.statusdefinition')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_to', to='tickets.statusdefinition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_exceptions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_exceptions', to='tickets.workspace')),
            ],
            options={
                'db_table': 'transition_exceptions',
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'from_status', 'to_status', 'exception_type', 'user')},
            },
        ),
    ]
