# Generated by Django 6.0.2 on 2026-02-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agent_type',
            new_name='user_type',
        ),
    ]
