# Generated by Django 6.0.3 on 2026-03-15 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_transitionexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdefinition',
            name='allowed_from',
            field=models.ManyToManyField(blank=True, help_text='If empty, can transition from any state. If set, only these source states are allowed.', related_name='can_lead_to', to='tickets.statusdefinition'),
        ),
        migrations.AddField(
            model_name='statusdefinition',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='If set, only these specific users can move tickets into this state (overrides who_can_enter)', related_name='allowed_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statusdefinition',
            name='who_can_enter',
            field=models.CharField(choices=[('all', 'All'), ('humans', 'Humans Only'), ('bots', 'Bots Only')], default='all', max_length=20),
        ),
    ]
