# Generated by Django 6.0.3 on 2026-03-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_statusdefinition_allowed_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdefinition',
            name='allowed_users',
        ),
    ]
