# Generated by Django 6.0.2 on 2026-02-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approval',
            field=models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved')], default='NEW', max_length=20),
        ),
    ]
