# Generated by Django 6.0.3 on 2026-03-15 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_statusdefinition_allowed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdefinition',
            name='who_can_enter',
        ),
        migrations.AddField(
            model_name='statusdefinition',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='If empty, anyone can enter. If set, only these users can enter.', related_name='enterable_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
