# Generated by Django 6.0.2 on 2026-02-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='approval',
        ),
        migrations.AddField(
            model_name='ticket',
            name='approved_status',
            field=models.CharField(choices=[('UNAPPROVED', 'Unapproved'), ('APPROVED', 'Approved')], default='UNAPPROVED', max_length=20),
        ),
    ]
