# Generated by Django 4.2.28 on 2026-03-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_statusdefinition_who_can_enter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdefinition',
            name='is_bot_requires_approval',
        ),
    ]
