# Generated by Django 6.0.3 on 2026-03-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_statusdefinition_is_bot_requires_approval'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_entity'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='idx_ticket_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project', 'status'], name='idx_ticket_project_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to'], name='idx_ticket_assigned_to'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='idx_ticket_created_at'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['resolved_at'], name='idx_ticket_resolved_at'),
        ),
    ]
