# Generated by Django 6.0.2 on 2026-02-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_approval_ticket_approved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('IN_TESTING', 'In Testing'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('BLOCKED', 'Blocked')], default='OPEN', max_length=20),
        ),
    ]
