# Generated by Django 6.0.3 on 2026-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_add_restrict_status_to_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='licensed_seats',
            field=models.PositiveIntegerField(default=3, help_text='Number of seats purchased for this workspace'),
        ),
        migrations.AlterField(
            model_name='projectagent',
            name='can_approve_tickets',
            field=models.BooleanField(default=False, help_text='Deprecated — approval gates removed'),
        ),
        migrations.AlterField(
            model_name='statusdefinition',
            name='is_terminal',
            field=models.BooleanField(default=False, help_text='Deprecated — terminal state concept removed'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='approved_status',
            field=models.CharField(default='UNAPPROVED', help_text='Deprecated — approval gates removed', max_length=20),
        ),
    ]
