# Generated by Django 6.0.2 on 2026-02-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_add_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Short prefix for ticket slugs, e.g. SA', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, help_text='Project-scoped ticket number', null=True),
        ),
    ]
