# Generated by Django 6.0.3 on 2026-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_statusdefinition_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdefinition',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional description of what this status means', max_length=200),
        ),
    ]
