# Generated by Django 6.0.2 on 2026-02-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_status_state_machine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspaceinvite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workspacemember',
            options={'ordering': ['joined_at']},
        ),
        migrations.AddField(
            model_name='projectagent',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
        migrations.AlterField(
            model_name='statusdefinition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statustransition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
