# Generated by Django 6.0.3 on 2026-03-19 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_seed_status_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Phase name, e.g. 'MVP', 'Beta Launch'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Goals and scope of this phase')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=False, help_text='Currently active phase')),
                ('started_at', models.DateTimeField(blank=True, help_text='When this phase started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this phase was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='tickets.project')),
            ],
            options={
                'db_table': 'phases',
                'ordering': ['position'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
