# Generated by Django 6.0.3 on 2026-03-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_add_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Project notes for bots — process guidelines, conventions, important context'),
        ),
    ]
