# Generated by Django 6.0.2 on 2026-02-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_set_all_workspace_members_to_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacemember',
            name='role',
        ),
    ]
