# Generated by Django 6.0.3 on 2026-03-19 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_add_project_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='is_active',
        ),
        migrations.AddField(
            model_name='phase',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='UPCOMING', help_text='Phase status', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='current_phase',
            field=models.ForeignKey(blank=True, help_text='The currently active phase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_project', to='tickets.phase'),
        ),
    ]
