# Generated by Django 6.0.3 on 2026-03-19 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_phase_status_and_current_phase_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdefinition',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Deprecated — use ProjectStatusPermission instead. Kept for backwards compat.', related_name='enterable_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectStatusPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users allowed to move tickets into this status on this project. Empty = remove override (anyone can enter).', related_name='project_enterable_statuses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_permissions', to='tickets.project')),
                ('status_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to='tickets.statusdefinition')),
            ],
            options={
                'db_table': 'project_status_permissions',
                'unique_together': {('project', 'status_definition')},
            },
        ),
    ]
