# Generated by Django 6.0.2 on 2026-03-06 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_remove_role_from_workspacemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(help_text='Full post content (HTML or Markdown)')),
                ('excerpt', models.TextField(blank=True, default='', help_text='Short summary for listings', max_length=500)),
                ('featured_image_url', models.URLField(blank=True, default='', help_text='Optional featured image URL', max_length=500)),
                ('meta_title', models.CharField(blank=True, default='', help_text='SEO meta title (falls back to title)', max_length=255)),
                ('meta_description', models.CharField(blank=True, default='', help_text='SEO meta description (falls back to excerpt)', max_length=320)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
