# Generated by Django 6.0.2 on 2026-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdefinition',
            name='is_bot_requires_approval',
            field=models.BooleanField(default=False, help_text='Bots need ticket approval before entering this state'),
        ),
    ]
