# Generated by Django 6.0.3 on 2026-03-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_migrate_allowed_users_to_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinvite',
            name='project',
            field=models.ForeignKey(blank=True, help_text='If set, joining this invite also adds the user to this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tickets.project'),
        ),
    ]
