# Generated by Django 4.2.28 on 2026-03-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_statusdefinition_is_bot_requires_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectagent',
            name='can_approve_tickets',
            field=models.BooleanField(default=False, help_text='Whether this agent can approve tickets in this project'),
        ),
    ]
