# Generated by Django 6.0.3 on 2026-03-19 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_add_project_to_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvite',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Deprecated — use ProjectInvite instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invites', to='tickets.project'),
        ),
        migrations.CreateModel(
            name='ProjectInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_project_invites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tickets.project')),
            ],
            options={
                'db_table': 'project_invites',
                'ordering': ['-created_at'],
            },
        ),
    ]
