# Generated by Django 4.2.28 on 2026-03-13 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_projectagent_can_approve_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=tickets.models.media_upload_path)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=10)),
                ('content_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='tickets.workspace')),
            ],
            options={
                'db_table': 'media_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
