# Generated by Django 4.2.29 on 2026-04-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_unarchive_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_in_workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace where this bot was created (bots only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bots', to='tickets.workspace'),
        ),
    ]
