# Generated by Django 4.2.29 on 2026-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_backfill_bot_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's email has been verified"),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address this OTP is for', max_length=254)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('purpose', models.CharField(choices=[('verify_email', 'Email Verification'), ('reset_password', 'Password Reset')], help_text='What this OTP is for', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires')),
                ('used', models.BooleanField(default=False, help_text='Whether this OTP has been used')),
            ],
            options={
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose'], name='idx_otp_email_purpose'), models.Index(fields=['expires_at'], name='idx_otp_expires')],
            },
        ),
    ]
