# Generated by Django 4.2.29 on 2026-04-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_fix_status_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the template', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, help_text='What this workflow is for')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this template is publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_template', to='tickets.workspace')),
            ],
            options={
                'db_table': 'community_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
