# Generated by Django 4.2.29 on 2026-04-02 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_add_community_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitytemplate',
            options={'ordering': ['-rating_sum', '-sync_count', '-created_at']},
        ),
        migrations.AddField(
            model_name='communitytemplate',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Number of ratings'),
        ),
        migrations.AddField(
            model_name='communitytemplate',
            name='rating_sum',
            field=models.IntegerField(default=0, help_text='Sum of all ratings'),
        ),
        migrations.AddField(
            model_name='communitytemplate',
            name='sync_count',
            field=models.IntegerField(default=0, help_text='Number of times this template has been synced'),
        ),
        migrations.CreateModel(
            name='CommunityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Rating 1-5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tickets.communitytemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_ratings',
                'unique_together': {('template', 'user')},
            },
        ),
    ]
