# Generated by Django 4.2.29 on 2026-04-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_remove_owner_from_project_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='about_text',
            field=models.TextField(blank=True, help_text='What this project is about'),
        ),
        migrations.AlterField(
            model_name='project',
            name='process_text',
            field=models.TextField(blank=True, default='', help_text='Process guidelines for bots — conventions, rules, workflow'),
        ),
        migrations.CreateModel(
            name='WorkspaceMemberProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='tickets.workspacemember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_member_projects', to='tickets.project')),
            ],
            options={
                'db_table': 'workspace_member_projects',
                'ordering': ['joined_at'],
                'unique_together': {('member', 'project')},
            },
        ),
    ]
