# Generated by Django 4.2.29 on 2026-04-02 15:08

from django.db import migrations


def migrate_project_agents_to_workspace_member_projects(apps, schema_editor):
    """
    Migrate data from ProjectAgent to WorkspaceMemberProject.
    For each ProjectAgent, find or create the corresponding WorkspaceMember,
    then create a WorkspaceMemberProject.
    """
    ProjectAgent = apps.get_model('tickets', 'ProjectAgent')
    WorkspaceMember = apps.get_model('tickets', 'WorkspaceMember')
    WorkspaceMemberProject = apps.get_model('tickets', 'WorkspaceMemberProject')
    
    for project_agent in ProjectAgent.objects.select_related('project', 'agent'):
        # Find or create the WorkspaceMember
        workspace_member, created = WorkspaceMember.objects.get_or_create(
            workspace=project_agent.project.workspace,
            user=project_agent.agent,
        )
        
        # Create the WorkspaceMemberProject (ignore if already exists)
        WorkspaceMemberProject.objects.get_or_create(
            member=workspace_member,
            project=project_agent.project,
            defaults={
                'role': project_agent.role,
                'joined_at': project_agent.joined_at,
            }
        )


def reverse_migration(apps, schema_editor):
    """
    Reverse: delete all WorkspaceMemberProject records.
    We don't reconstruct ProjectAgent records since this is one-way.
    """
    WorkspaceMemberProject = apps.get_model('tickets', 'WorkspaceMemberProject')
    WorkspaceMemberProject.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_add_workspace_member_project'),
    ]

    operations = [
        migrations.RunPython(
            migrate_project_agents_to_workspace_member_projects,
            reverse_migration,
        ),
    ]
