# Generated by Django 4.2.29 on 2026-04-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_migrate_project_agents_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.URLField(blank=True, help_text='Project logo URL', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Project website URL', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Public description of what this workspace does'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this workspace can be viewed publicly'),
        ),
    ]
