# Generated by Django 4.2.29 on 2026-04-02 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_project_logo_project_url_workspace_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('sync_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_templates', to='tickets.workspace')),
            ],
            options={
                'db_table': 'state_templates',
                'ordering': ['-sync_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StateTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('allowed_from_keys', models.JSONField(blank=True, default=list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.statetemplate')),
            ],
            options={
                'db_table': 'state_template_items',
                'ordering': ['order'],
                'unique_together': {('template', 'key')},
            },
        ),
    ]
