# Generated by Django 4.2.29 on 2026-04-03 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_add_state_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.phase'),
        ),
    ]
