# Generated by Django 4.2.29 on 2026-04-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_add_is_public_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Public website URL — shown on community profile as a backlink', max_length=500),
        ),
    ]
