# Generated by Django 6.0.3 on 2026-04-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_remove_project_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether this member has been approved by the workspace owner. Bots start as unapproved.'),
        ),
        migrations.DeleteModel(
            name='WorkspaceInvite',
        ),
        migrations.RunSQL(
            'DROP TABLE IF EXISTS workspace_invites;',
            reverse_sql='',  # No reverse — table is gone
        ),
    ]
