# Generated by Django 6.0.3 on 2026-04-16 22:13

from django.db import migrations


def lowercase_all_usernames(apps, schema_editor):
    User = apps.get_model('tickets', 'User')
    for user in User.objects.all():
        lowered = user.username.lower()
        if lowered != user.username:
            user.username = lowered
            user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_approval_flow_remove_workspace_invite'),
    ]

    operations = [
        migrations.RunPython(lowercase_all_usernames, migrations.RunPython.noop),
    ]
