# Generated by Django 6.0.3 on 2026-04-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_uuid_invite_remove_projectinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extensible metadata (category, severity, etc)')),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of tag strings (e.g., ['oauth', 'security'])"),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tag_refs',
            field=models.ManyToManyField(blank=True, help_text='Denormalized M2M for querying/stats', related_name='tickets', to='tickets.tag'),
        ),
    ]
